name: Lint

on: [pull_request]

jobs:
  spelling:
    name: spelling
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm
    - run: npm ci
    - run: npm run ci:spelling
  syncpack:
    name: versions
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm
    - run: npm ci
    - run: npm run ci:versions
